"""empty message

Revision ID: ecca23a8bfab
Revises: 9744c15fc69d
Create Date: 2023-06-20 20:31:18.924774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecca23a8bfab'
down_revision = '9744c15fc69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_group_id_groups_id', type_='foreignkey')
        batch_op.drop_constraint('fk_users_owned_group_id_groups_id', type_='foreignkey')
        batch_op.drop_column('owned_group_id')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('owned_group_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_owned_group_id_groups_id', 'groups', ['owned_group_id'], ['id'])
        batch_op.create_foreign_key('fk_users_group_id_groups_id', 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###